[package]
name = "amphora"
version = "0.1.0"
authors = ["Ilkka Rauta <ilkka.rauta@gmail.com>"]

[dependencies.encoding]
version = "0.2"

[dependencies.bitreader]
git = "https://github.com/irauta/bitreader.git"
